@api = http://localhost:3001/user

### todos los usuarios
GET  {{api}}/api
### usuario por id
GET  {{api}}/api/baQ9W9VydRUo4SFYNg61

### todos los usuarios mayores de edad
GET  {{api}}/api/mayoredad
### crear un usuario
POST  {{api}}/api
content-type: application/json

{
    "nombre":"ana",
    "edad": 60,
    "email": "zena@mail.com"
}
### editar un usuario
PUT  {{api}}/api/ppjyyyn6VBioh25tq5H3
content-type: application/json

{
    "nombre":"Carlos",
     "email": "carlos-m@mail.com",
     "edad" : 45
}
### eliminar un usuario
DELETE  {{api}}/api/vbeVm5KzBfu32E9h4RUK