@api = http://localhost:3001/user

### todos los usuarios
GET  {{api}}/api
content-type: application/json

{
    "password": "Amaria@12345",
    "email": "maria@mail.com",
    "username": "mari21"
}
### usuario por id
GET  {{api}}/api/baQ9W9VydRUo4SFYNg61
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.com",
    "password": "Pedro%&hgsjo5"

}

### todos los usuarios mayores de edad
GET  {{api}}/api/mayoredad
content-type: application/json

{
    "password": "Amaria@12345",
    "email": "maria@mail.com",
    "username": "mari21"
}
### crear un usuario
POST  {{api}}/api
content-type: application/json

{
    "username": 45,
    "nombre":"pedro casado",
    "edad": 25,
    "email": "pedro2@mail.com",
    "password":"Pedro%&hgsjo5"
}

### login un usuario
POST  {{api}}/api/login
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.com",
    "password": "Pedro%&hgsjo5"
}
### editar un usuario
PUT  {{api}}/api/0Br2dqLiIWLeMLdhT54m
content-type: application/json

{
    "password": "Amaria@12345",
    "email": "maria@mail.com",
    "username": "mari21",
    
    "usernameNew": 45,
    "emailNew": 45,
    "edadNew": "15",
    "nombreNew": 45,
    "passwordNew": "A2345"
}
### eliminar un usuario
DELETE  {{api}}/api/uimdUntKPzZDzyuyEuyF
content-type: application/json

{
    "password": "Amaria@12345",
    "email": "maria@mail.com",
    "username": "mari21"
}