@api = http://localhost:3001/user

### todos los usuarios
GET  {{api}}/api
content-type: application/json

{
    "password": "Amaria@12345",
    "email": "maria@mail.com",
    "username": "mari21"
}
### usuario por id
GET  {{api}}/api/4UXl2czBcw39uNsOJBy2
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.com",
    "password": "Pedro%&hgsjo5"

}

### todos los usuarios mayores de edad
GET  {{api}}/api/mayoredad
content-type: application/json

{
    "password": "Amaria@12345",
    "email": "maria@mail.com",
    "username": "mari21"
}
### crear un usuario
POST  {{api}}/api
content-type: application/json

{
    "username": "jo",
    "nombre":"jose marcano",
    "edad": 21,
    "email": "marnoj@mail.com",
    "password":"Jose1%&hgsjo5"
}

### subir imagen
POST  {{api}}/api/image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

5oBYonB5zZQm814sJbkd
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="pdf.pdf"
Content-Type: image/jpeg

< ./pdf.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### login un usuario
POST  {{api}}/api/login
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.com",
    "password": "Pedro%&hgsjo5"
}
### editar un usuario
PUT  {{api}}/api/4UXl2czBcw39uNsOJBy2
content-type: application/json

{
    "password": "Jose1%&hgsjo5",
    "email": "marcano-j@mail.com",
    "username": "joseito",
    
    "usernameNew": "pedrito",
    "emailNew": "pedro@mail.com",
    "edadNew": 15,
    "nombreNew": "PEDRO CASADO",
    "passwordNew": "Pedro%&hgsjo5"
}
### eliminar un usuario
DELETE  {{api}}/api/uimdUntKPzZDzyuyEuyF
content-type: application/json

{
    "password": "Amaria@12345",
    "email": "maria@mail.com",
    "username": "mari21"
}