@api = http://localhost:3002/user

### todos los usuarios
GET  {{api}}/api
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.com",
    "password": "Pedro%&hgsjo5"
}
### usuario por id
GET  {{api}}/api/5oBYonB5zZQm814sJbkd
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.com",
    "password": "Pedro%&hgsjo5"

}

### todos los usuarios mayores de edad
GET  {{api}}/api/mayoredad
content-type: application/json

{
    "password": "Amaria@12345",
    "email": "maria@mail.com",
    "username": "mari21"
}
### crear un usuario
POST  {{api}}/api
content-type: application/json

{
    "username": "mario23",
    "edad": 28,
    "email": "mario@mail.com",
    "password":"Mario%&h415jo5"
}

### subir imagen
POST  {{api}}/api/image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

5oBYonB5zZQm814sJbkd
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="prueba.jpeg"
Content-Type: image/jpeg

< ./prueba.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### login un usuario
POST  {{api}}/api/login
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.co",
    "password": "Pedro%&hgsjo5"
}
### editar un usuario
PUT  {{api}}/api/0Br2dqLiIWLeMLdhT54m
content-type: application/json

{
    "password": "Jose1%&hgsjo5",
    "email": "marcano-j@mail.com",
    "username": "joseito",
    
    "usernameNew": "mari25",
    "emailNew": "mariaEdit@mail.com",
    "edadNew": 16,
    "nombreNew": "MARIA ALEJANDRA",
    "passwordNew": "Amaria@12345"
}
### eliminar un usuario
DELETE  {{api}}/api/BoNjwsCYWBh2Qb9aAbp0
content-type: application/json

{
    "password": "Amaria@12345",
    "email": "maria@mail.com",
    "username": "mari21"
}