@api = http://localhost:3002/v1/user

### todos los usuarios
GET  {{api}}/api
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.com",
    "password": "Pedro%&hgsjo5"
}
### usuario por id
GET  {{api}}/api/5oBYonB5zZQm814sJbkd 
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.com",
    "password": "Pedro%&hgsjo5"

}

### todos los usuarios mayores de edad
GET  {{api}}/api/mayoredad
content-type: application/json

{
    "password": "Amaria&123455",
    "email": "antonio3@mail.com",
    "username": "anita"
}
### crear un usuario
POST  {{api}}/api
content-type: application/json

{
    "username": "antoni",
    "nombre": "antonio montechiaro",
    "edad": 18,
    "email": "antonio@mail.com",
    "password":"anton45MAR@%&"
}

### subir imagen
POST  {{api}}/api/image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

5oBYonB5zZQm814sJbkd
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

angelita
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

Delgo%&hgsjo5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

angela-delg@mail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="prueba.jpeg"
Content-Type: image/jpeg

< ./prueba.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
### eliminar una imagen
DELETE  {{api}}/api/image
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.com",
    "password": "Pedro%&hgsjo5",
    "linkImage" : "usuarios1655992149492.jpeg"

}

### login un usuario
POST  {{api}}/api/login
content-type: application/json

{
    "username": "angel21",
    "email": "angel@mail.com",
    "password": "Amaria@12345"
}
### editar un usuario
PUT  {{api}}/api/7EC3Pr4AmSHhCNEXQvs7
content-type: application/json

{
    "username": "pedrito",
    "email": "pedro@mail.com",
    "password": "Pedro%&hgsjo5",
    
    "usernameNew": "joseito4",
    "emailNew": "marcano-j@mail.com",
    "edadNew": 26,
    "linkImage": "",
    "nombreNew": "JOSE ALEJANDRO MARCANO lopez",
    "passwordNew": "Jose1%&hgsjo5"
}
### eliminar un usuario
DELETE  {{api}}/api/BoNjwsCYWBh2Qb9aAbp0
content-type: application/json

{
    "password": "Amaria@12345",
    "email": "maria@mail.com",
    "username": "mari21"
}